apiVersion: batch/v1
kind: Job
metadata:
  name: r
  namespace: dev
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db
            optional: false
        - secretRef:
            name: vatusa-api-key
            optional: false
        image: vchicago/job-roster-sync:dev
        imagePullPolicy: Always
        name: r
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
