apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kzdv-dev
  namespace: core
spec:
  secretName: -tls
  issuerRef:
    name: letsencrypt-zdv
    kind: ClusterIssuer
  dnsNames:
  - pma.kzdv.cloud
