apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chicagoartcc-org
  namespace: prod
spec:
  secretName: chicagoartcc-org-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - chicagoartcc.org
  - '*.chicagoartcc.org'
  - '*.dev.chicagoartcc.org'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vzau-cloud
  namespace: prod
spec:
  secretName: vzau-cloud-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - vzau.cloud
  - '*.vzau.cloud'
  - '*.dev.vzau.cloud'
